name: deploy docs

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install -U sphinx
          python -m pip install furo myst-parser
          python -m pip install -r docs/requirements.txt
      - name: Clear cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
            ./docs/_build
          key: ${{ runner.os }}-docs-${{ hashFiles('docs/requirements.txt') }}          
      - name: Make docs
        run: |
          cd docs/
          make html
      - name: run ghp-import
        run: |
          python -m pip install ghp-import
          ghp-import -n -p -f ./docs/_build/html
